retrain:
  schedule: "0 */6 * * *"     # Cron chạy mỗi 6 tiếng (ví dụ)
  image:
    repository: docker.io/bqmxnh/cloud-ops-retrain
    tag: "20251214093100"
    pullPolicy: Always

  resources:
    cpu: "2"
    memory: "4Gi"

  mlflowUrl: "https://mlflow.qmuit.id.vn"
  modelName: "ARF Baseline Model"
  s3Bucket: "qmuit-training-data-store"
  region: "us-east-1"
