apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ids-mlflow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bqmxnh/manifests-cloud-ops.git
    targetRevision: main
    path: values/mlflow
  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true