repoURL: https://github.com/bqmxnh/manifests-cloud-ops.git
targetRevision: main

api:
  path: values/api

mlflow:
  path: values/mlflow

storageclass:
  path: values/storageclass

argoWorkflows:
  path: values/argo-workflows
