repoURL: https://github.com/bqmxnh/manifests-cloud-ops.git
targetRevision: main

api:
  path: values/api

mlflow:
  path: values/mlflow

retrainCron:
  schedule: "0 3 * * *"
  image: "docker.io/bqmxnh/cloud-ops-retrain:latest"
  resources:
    cpu: "2"
    memory: "4Gi"
