repoURL: https://github.com/bqmxnh/manifests-cloud-ops.git
targetRevision: main

api:
  path: values/api

mlflow:
  path: values/mlflow

retrain:
  image:
    repository: bqmxnh/cloud-ops-retrain
    tag: "20251206191003"
    pullPolicy: Always

  schedule: "0 3 * * *"

  resources:
    cpu: "2"
    memory: "4Gi"
