apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
  labels:
    app: mlflow-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-service
  template:
    metadata:
      labels:
        app: mlflow-service
    spec:

      initContainers:
        - name: init-mlflow-dir
          image: busybox
          command: ["sh", "-c", "mkdir -p /mlflow && chmod -R 777 /mlflow"]
          volumeMounts:
            - name: mlflow-storage
              mountPath: /mlflow

      containers:
        - name: mlflow
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.service.targetPort }}

          env:
            - name: BACKEND_STORE_URI
              value: "{{ .Values.env.BACKEND_STORE_URI }}"
            - name: ARTIFACT_ROOT
              value: "{{ .Values.env.ARTIFACT_ROOT }}"
            - name: AWS_DEFAULT_REGION
              value: "{{ .Values.env.AWS_DEFAULT_REGION }}"
            - name: MLFLOW_S3_IGNORE_TLS
              value: "{{ .Values.env.MLFLOW_S3_IGNORE_TLS }}"
            - name: MLFLOW_ALLOW_EVERYONE
              value: "true"

          command: ["mlflow"]
          args:
            - server
            - --backend-store-uri=$(BACKEND_STORE_URI)
            - --default-artifact-root=$(ARTIFACT_ROOT)
            - --host=0.0.0.0
            - --port={{ .Values.service.targetPort }}
            - --workers=1

          volumeMounts:
            - name: mlflow-storage
              mountPath: /mlflow

      volumes:
        - name: mlflow-storage
          emptyDir: {}
