apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
  labels:
    app: mlflow-service
spec:
  type: ClusterIP
  selector:
    app: mlflow-service
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
