name: Update Helm Chart

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "New Docker image tag"
        required: true
        type: string

  repository_dispatch:
    types: [update-helm]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Get image tag from event
        id: get_tag
        run: |
          if [ "${{ github.event_name }}" = "repository_dispatch" ]; then
            echo "tag=${{ github.event.client_payload.image_tag }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ inputs.image_tag }}" >> $GITHUB_OUTPUT
          fi

      - name: Update Helm values with new image tag
        run: |
          sed -i 's|tag:.*|tag: "'"${{ steps.get_tag.outputs.tag }}"'"|g' values/api/values.yaml

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add values/api/values.yaml
          git commit -m "Update API image tag to ${{ steps.get_tag.outputs.tag }}" || echo "Nothing to commit"

      - name: Push changes using PAT
        run: |
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/bqmxnh/manifests-cloud-ops.git HEAD:main